### PR TITLE
Use native build instead of x86/jetson target

### PR DESCRIPTION
**Pull request by lida2003**
Discussion: [ Ignore msposd_jetson for gs on jetson orin #29 ](https://github.com/OpenIPC/msposd/pull/29)

### CODE REVIEW

**Comment by lida2003** [comment]
```
sudo apt-get update
sudo apt-get upgrade
```

Untitled

**Comment by henkwiedig** [comment]
Testbuild looks fine, hi3536dv100_fpv doesn't build locally as well with main. So no regression for that.
When you want to locally run msposd on x86 you will need receiving hardware, setup the msp stream to receive from the drone. Just like on jetson. Then use gstreamer to start the video and overlay it with msposd. The screenshot you postet is what you will get when msposd is runnig and no mspdata is received. So this is expected with no forther config.

What about the DISPLAY envvar ? I now testest more then 3 ways to set this on remote ssh session.
`ssh ... 'export DISPLAY=:0; msposd ...`
`ssh -o SendEnv=DISPLAY root@.... msposd....`
`edit .bashrc`
The way it is now we completely disable other users to set the DISPLAY as they wish.
Unless there is really good reason for this i think this should be removed.

**Comment by lida2003** [comment]
If you don't use it, then a segfault when launching from ssh.

**Comment by henkwiedig** [comment]
Yes, but why setting this in the application, especially forcefully overwrite it ?
You can use one of the million other way to set the DISLPLAY ?
There might be setups with two displays, one for Video one for telemetry/mission plan.
The user will not have the option to choose which is which.

**Comment by lida2003** [comment]
> Yes, but why setting this in the application, especially forcefully overwrite it ? 

Not forcefully. 

> You can use one of the million other way to set the DISLPLAY ? There might be setups with two displays, one for Video one for telemetry/mission plan. The user will not have the option to choose which is which.

That's what I consider. 
- As I have said if launch from ssh, it will segfault. 
- If you have env set, then posix api did as user set.
- If you haven't set, posix api will ask, and set default to current active display.

Then to provide code's robustness of NOT properly setting env, casuing segfault issue.

**Comment by henkwiedig** [comment]
`setenv("DISPLAY", ":0", 0);` does what you want, without the `if (getenv("DISPLAY") == NULL) ...`

**Comment by lida2003** [comment]
> `setenv("DISPLAY", ":0", 0);` does what you want, without the `if (getenv("DISPLAY") == NULL) ...`

This is what we mean: if we don't have this env, it will segfault. If there is no display set, then we simply use default display.
It's a straight forward way to do the default setting. Of course, use can set other values, then there will NOT be NULL.

https://github.com/SnapDragonfly/msposd/blob/cabc6b8ade29112f63a5a8a5621e02240d0c3a13/osd/util/Render_x86.c#L79-L85

**Comment by henkwiedig** [comment]
this
```
setenv("DISPLAY", ":0", 0); 
```
is equivalant to this:
```
         if (getenv("DISPLAY") == NULL) { 
             /* 
              * Use default display screen, especially launch from console 
              * ToDo: x86 linux should implement this code also, test needed. 
              */ 
             setenv("DISPLAY", ":0", 1); 
         } 
```

hence the "0". from `man 3 setenv`
```
.... If name does exist in the environment, then its value is changed to value if overwrite is nonzero; if overwrite is zero, then the value of name is not changed ....
```

**Comment by lida2003** [comment]
You can do the test. If you don't have this code. It'll be a segfault.

**Comment by henkwiedig** [comment]
Yes just use the non overwrite option from setenv. "0" as thid argument. Then the whole if part is useless.
We can also remove the ifdef.

**Comment by lida2003** [comment]
@henkwiedig It doesn't work on jetson. 

Can you check if the below is what we meant to do.

If I didn't mis-understand, please let me know about [setenv](https://www.ibm.com/docs/en/zos/2.4.0?topic=support-posix-functions-getenv-setenv-clearenv)

I think lanuching from remote ssh(putty) mgiht be different or something about the understanding of the posix API.

```
daniel@daniel-nvidia:~/Work/msposd/release/jetson$ echo $DISPLAY

daniel@daniel-nvidia:~/Work/msposd/release/jetson$ ./msposd --master 127.0.0.1:14560  --osd -r 50 --ahi 1 --matrix 11 -v
Ver: 8a82c65-dirty Compiled at: 20241127_153132
Listen on port :127.0.0.1:14560
MSP to OSD mode!Verbose mode!Majestic width:1920,height:1080
Cannot open display
Loading /home/daniel/Work/msposd/release/jetson/font.png for 1000p mode
Font file res 36:13824 pages:1
Loading small size glyphs /home/daniel/Work/msposd/release/jetson/font_hd.png for 1000p mode
Glyph size:36:54 on a 53:20 matrix. Overlay 1912:1080
Create_region PixelFormat:11 Size: 1912:1080 X_Offset:8 Y_Offset:0 results: -1
Segmentation fault (core dumped)
daniel@daniel-nvidia:~/Work/msposd/release/jetson$ git diff
diff --git a/osd/util/Render_x86.c b/osd/util/Render_x86.c
index a49942b..9f42317 100644
--- a/osd/util/Render_x86.c
+++ b/osd/util/Render_x86.c
@@ -72,20 +72,8 @@ int Init_x86(uint16_t *width, uint16_t *height) {
             forcefullscreen=false;
 #ifdef _DEBUG_x86
         forcefullscreen=false;
+        setenv("DISPLAY", ":0", 0);
 #endif
-
-
-#ifdef _x86
-        if (getenv("DISPLAY") == NULL) {
-            /*
-             * Use default display screen, especially launch from console
-             * ToDo: x86 linux should implement this code also, test needed.
-             */
-            setenv("DISPLAY", ":0", 1);
-        }
-#endif
-
-

         display = XOpenDisplay(NULL);
         if (!display) {
```

**Comment by lida2003** [comment]
> _DEBUG_x86 was set durting compile time ?

YES

**Comment by lida2003** [comment]
@henkwiedig 
Ah..... it's `_DEBUG_x86` not `_x86`

what this MACRO for?

**Comment by lida2003** [comment]
@henkwiedig I'll left `_DEBUG_x86 ` as it is. Just optimize `setenv` for native build.

**Comment by henkwiedig** [comment]
Can you rabse this an main. It conflicts with the version.h PR.

@tipoman9 If you don't veto I would merge this.

**Comment by tipoman9** [comment]
@henkwiedig Sure, go ahead.

**Comment by lida2003** [comment]
@henkwiedig rebased and worked on jetson.

```
daniel@daniel-nvidia:~/Work/msposd$ file msposd
msposd: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=a3fbab226e66a20534c2a495de18003b63d52610, for GNU/Linux 3.7.0, with debug_info, not stripped
daniel@daniel-nvidia:~/Work/msposd$ cat version.h
#ifndef VERSION_H
#define VERSION_H
#define GIT_VERSION "a4ff7f6"
#endif // VERSION_H
daniel@daniel-nvidia:~/Work/msposd$ git log -n 1
commit a4ff7f61675b78f06289a29eb5e1ec31ba552824 (HEAD -> pr_use_native_build, origin/pr_use_native_build)
Author: Daniel Li <lida_mail@163.com>
Date:   Wed Nov 27 15:59:10 2024 +0800

    Optimize setenv for native build
daniel@daniel-nvidia:~/Work/msposd$ cp msposd ./release/jetson/msposd
daniel@daniel-nvidia:~/Work/msposd$ cd ./release/jetson/
daniel@daniel-nvidia:~/Work/msposd/release/jetson$ ./msposd --master 127.0.0.1:14560  --osd -r 50 --ahi 1 --matrix 11 -v
Ver: a4ff7f6 Compiled at: 20241128_083816
Listen on port :127.0.0.1:14560
MSP to OSD mode!Verbose mode!Majestic width:1920,height:1080
Loading /home/daniel/Work/msposd/release/jetson/font.png for 1080p mode
I4 40:13824 Stride:20
Font file res 40:13824 pages:1
Loading small size glyphs /home/daniel/Work/msposd/release/jetson/font_hd.png for 1080p mode
I4 24:9216 Stride:12
Glyph size:36:54 on a 53:20 matrix. Overlay 1920:1080
Glyph size:36:54 on a 53:20 matrix. Overlay 1920:1080
Create_region PixelFormat:3 Size: 1920:1080 X_Offset:0 Y_Offset:0 results: -1
set_LOGO with u32Height:1080 enPixelFormat 3
Listening UDP on 127.0.0.1:14560...
```

**Pull request merged**
