### PR TITLE
Ignore msposd_jetson for gs on jetson orin

### PR DESCRIPTION
**Pull request by lida2003**

### CODE REVIEW

**Comment by henkwiedig** [comment]
@lida2003 what is the point in having a jetson architecture in the first place ? The only useful difference to x86 is the environment setting.
Is there a problem running msposd useing `DISPLAY=:0 msposd` on jetson ?

**Comment by henkwiedig** [comment]
At best you provide a cross compile integration for build.sh like all other architectures currently do.
Like here: https://docs.nvidia.com/jetson/archives/r35.2.1/DeveloperGuide/text/AT/JetsonLinuxToolchain.html

**Comment by lida2003** [comment]
> Is there a problem running msposd useing `DISPLAY=:0 msposd` on jetson ?

I got it running without any problem on jetson.

**Comment by lida2003** [comment]
@henkwiedig Hope there is jetson gs, which is something like radax. Then it'll be much more specific cross-compile tool.

**Comment by henkwiedig** [comment]
Still don't get it. Currently the jetson architecture adds nothing to the project.
It's just another way to call the system native build tools.
You locally could just use build.sh x86 end end up with the same binary. (just named msposd_x86)
But for all others there is no central usage.

Maybe we should rework build.sh do do either xcompile (goke|hisi|star6b0|star6e) or use system native build environment (x86|jetson). This could also be used on radxa when building on radxa directly.

**Comment by lida2003** [comment]
there are two points:
1. compile tool - cross compile or native build
2. binary target - for different target board
3. application binary - moposd

msposd_xxx, those xxx stands for target board.

Normally we use buildroot to build rootfs, compiling application. There is no such name, msposd_xxx. 

The build.sh is a script to simple build msposd for different target, using cross compile tool or native tool to generate msposd_xxx target, then copied to release/xxx/ dir.

That's what build tool and those names for.

**Comment by henkwiedig** [comment]
I thought about modifying build.sh as follows:
```
if [ "$1" = "goke" ]; then
	DRV=$PWD/firmware/general/package/goke-osdrv-gk7205v200/files/lib
	make -B CC=$GCC DRV=$DRV TOOLCHAIN=$PWD/toolchain/$CC OUTPUT=$OUT $1
elif [ "$1" = "hisi" ]; then
	DRV=$PWD/firmware/general/package/hisilicon-osdrv-hi3516ev200/files/lib
	make -B CC=$GCC DRV=$DRV TOOLCHAIN=$PWD/toolchain/$CC OUTPUT=$OUT $1
elif [ "$1" = "star6b0" ]; then
	DRV=$PWD/firmware/general/package/sigmastar-osdrv-infinity6b0/files/lib
	make -B CC=$GCC DRV=$DRV TOOLCHAIN=$PWD/toolchain/$CC OUTPUT=$OUT $1
elif [ "$1" = "star6e" ]; then
	DRV=$PWD/firmware/general/package/sigmastar-osdrv-infinity6e/files/lib
	make -B CC=$GCC DRV=$DRV TOOLCHAIN=$PWD/toolchain/$CC OUTPUT=$OUT $1
else
	DRV=$PWD
	make DRV=$DRV OUTPUT=$OUT native
fi
```
Additionally, I would add the native target to the Makefile while removing the x86 and jetson targets.
This approach ensures that building against the native toolchain is architecture-agnostic.
Only cross-compiled builds will rely on specific toolchains.

**Comment by lida2003** [comment]
Right now, the difference is below, which is for ssh remote launch. But it wouldn't on my laptop(x86). I hope it will work on other software stack (versions), as it's a common API. I don't know why it didn't work on my x86.

https://github.com/OpenIPC/msposd/blob/517c55ae3b95c9750b17f6dea916bd1fc305b71d/osd/util/Render_x86.c#L78-L86

**Comment by lida2003** [comment]
@henkwiedig  I think it works on my x86. You have to test before use, as my laptop is weird about this posix API.

https://github.com/OpenIPC/msposd/pull/31

**Comment by henkwiedig** [comment]
See: https://github.com/OpenIPC/msposd/pull/31

**Pull request closed without merging**
